export const OficiosConfig = {
  "Construcción y mantenimiento": [
    { value: "albanil", label: "Albañil" },
    { value: "pintor", label: "Pintor" },
    { value: "electricista", label: "Electricista" },
    { value: "plomero-gasista", label: "Plomero / Gasista" },
    { value: "carpintero", label: "Carpintero" },
    { value: "herrero", label: "Herrero / Soldador" },
    { value: "techista", label: "Techista" },
    { value: "yesero", label: "Yesero" },
    { value: "vidriero", label: "Vidriero" },
    { value: "aire-acondicionado", label: "Instalador de aire acondicionado" },
    { value: "jardinero", label: "Jardinero / Parquero" },
    { value: "otros", label: "Otros" },
  ],
  "Automotores": [
    { value: "mecanico", label: "Mecánico automotriz" },
    { value: "chapista", label: "Chapista" },
    { value: "pintor-autos", label: "Pintor de autos" },
    { value: "gomeria", label: "Gomería" },
    { value: "lavadero", label: "Lavadero de autos" },
    { value: "elect-auto", label: "Electricista del automotor" },
    { value: "otros", label: "Otros" },
  ],
  "Hogar y servicios personales": [
    { value: "limpieza", label: "Limpieza / Mucama" },
    { value: "niniera", label: "Niñera" },
    { value: "cuidado-mayores", label: "Cuidado de adultos mayores" },
    { value: "cocinero", label: "Cocinero / Panadero / Pastelero" },
    { value: "costurera", label: "Costurera / Modista" },
    { value: "peluquero", label: "Peluquero / Barbero" },
    { value: "manicura", label: "Manicura / Pedicura" },
    { value: "esteticista", label: "Esteticista" },
    { value: "otros", label: "Otros" },
  ],
  "Tecnología y comunicación": [
    { value: "tecnico-pc", label: "Técnico en PC / Redes" },
    { value: "celulares", label: "Reparador de celulares" },
    { value: "diseno-grafico", label: "Diseñador gráfico" },
    { value: "fotografo", label: "Fotógrafo" },
    { value: "community-manager", label: "Community Manager" },
    { value: "programador", label: "Desarrollador web / Programador" },
    { value: "otros", label: "Otros" },
  ],
  "Industria y producción": [
    { value: "tornero", label: "Tornero" },
    { value: "textil", label: "Operario textil" },
    { value: "metalurgico", label: "Operario metalúrgico" },
    { value: "elect-industrial", label: "Electricista industrial" },
    { value: "electromecanico", label: "Técnico electromecánico" },
    { value: "otros", label: "Otros" },
  ],
  "Transporte y logística": [
    { value: "chofer", label: "Chofer particular / remisero / taxista" },
    { value: "fletero", label: "Fletero" },
    { value: "motoquero", label: "Motoquero / Cadete" },
    { value: "repartidor", label: "Repartidor" },
    { value: "otros", label: "Otros" },
  ],
};
